---
- name: Create Traefik config directory
  ansible.builtin.file:
    path: /etc/traefik
    state: directory
    mode: "0755"

- name: Copy Traefik static config
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: /etc/traefik/traefik.yml
    mode: "0644"
  notify: Restart Traefik
