- name: Start minikube
  hosts: web
  become: true

  tasks:
    - name: Ensure runner home kube dir exists
      file:
        path: /home/github-runner/.kube
        state: directory
        owner: github-runner
        group: github-runner

    - name: Start minikube as github-runner
      become_user: github-runner
      command: minikube start --driver=docker
      args:
        creates: /home/github-runner/.minikube/profiles/minikube/config.json