name: Test Runner

on:
  push:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Say hello
        run: echo "Hello from Hetzner runner"

      - name: Check Docker
        run: docker --version

      - name: Check kubectl
        run: sudo KUBECONFIG=/root/.kube/config kubectl get nodes