name: Test Runner

on:
  push:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Say hello
        run: echo "Hello from Hetzner runner"

      - name: Check Docker
        run: docker --version

      - name: Check kubectl
        env:
            HOME: /home/github-runner
            KUBECONFIG: /home/github-runner/.kube/config
        run: kubectl get nodes